name: WebAPP build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'apps/client/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        uses: azure/docker-login@v2
        with:
          login-server: etherealpulse.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          cd apps/client
          docker build . -t etherealpulse.azurecr.io/webapp:${{ github.sha }}
          docker push etherealpulse.azurecr.io/webapp:${{ github.sha }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: etherealpulse.azurecr.io/webapp:${{ github.sha }}
          containerAppName: ethereal-pulse-webapp
          containerAppEnvironment: container-apps-env
          resourceGroup: RG-Ethereal-Pulse
          location: westeurope
          targetPort: 5173
          ingress: external
