name: WebAPP build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'apps/client/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to the Azure Container Registry
        run: az acr login --name etherealpulse

      - name: Build and push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: etherealpulse.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          echo ${{ github.WORKSPACE }}
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login etherealpulse.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker build /apps/client/Dockerfile . -t etherealpulse.azurecr.io/webapp:${{ github.run_id }}
          docker push etherealpulse.azurecr.io/webapp:${{ github.run_id }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: etherealpulse.azurecr.io/webapp:${{ github.run_id }}
          registryUrl: etherealpulse.azurecr.io
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: ethereal-pulse-webapp
          containerAppEnvironment: container-apps-env
          resourceGroup: RG-Ethereal-Pulse
          location: westeurope
          targetPort: 5173
          ingress: external
